name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  parity:
    uses: ./.github/workflows/versionParity.yml

  build:
    needs: parity
    if: needs.parity.outputs.is_prerelease == 'false'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
